# Generated by Django 3.2 on 2024-11-08 10:38

from django.db import migrations
import userlogin.models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='master_user',
            managers=[
                ('objects', userlogin.models.AccountManager()),
            ],
        ),
    ]
